application: feedsanitizer
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  
- url: /styles
  static_dir: static/styles

- url: /scripts
  static_dir: static/scripts

- url: /images
  static_dir: static/images

- url: /.*
  script: djangoappengine/main/main.py
